import type { Textbook } from "./types"

export const mockTextbooks: Textbook[] = [
  {
    id: "genki-1",
    name: "Genki I: An Integrated Course in Elementary Japanese",
    short_name: "Genki I",
    chapters: [
      {
        id: "genki-1-ch1",
        number: 1,
        title: "New Friends",
        parts: [
          {
            id: "genki-1-ch1-p1",
            name: "Genki 1 Ch.1 Part 1 of 4",
            partNumber: 1,
            totalParts: 4,
            description: "Greetings and Self-introductions",
            isImported: false,
          },
          {
            id: "genki-1-ch1-p2",
            name: "Genki 1 Ch.1 Part 2 of 4",
            partNumber: 2,
            totalParts: 4,
            description: "Numbers and Age",
            isImported: false,
          },
          {
            id: "genki-1-ch1-p3",
            name: "Genki 1 Ch.1 Part 3 of 4",
            partNumber: 3,
            totalParts: 4,
            description: "Time and Daily Activities",
            isImported: false,
          },
          {
            id: "genki-1-ch1-p4",
            name: "Genki 1 Ch.1 Part 4 of 4",
            partNumber: 4,
            totalParts: 4,
            description: "Family and Occupations",
            isImported: false,
          },
        ],
      },
      {
        id: "genki-1-ch2",
        number: 2,
        title: "Shopping",
        parts: [
          {
            id: "genki-1-ch2-p1",
            name: "Genki 1 Ch.2 Part 1 of 5",
            partNumber: 1,
            totalParts: 5,
            description: "School and Subjects",
            isImported: false,
          },
          {
            id: "genki-1-ch2-p2",
            name: "Genki 1 Ch.2 Part 2 of 5",
            partNumber: 2,
            totalParts: 5,
            description: "Things Around Us",
            isImported: false,
          },
          {
            id: "genki-1-ch2-p3",
            name: "Genki 1 Ch.2 Part 3 of 5",
            partNumber: 3,
            totalParts: 5,
            description: "Food and Drinks",
            isImported: false,
          },
          {
            id: "genki-1-ch2-p4",
            name: "Genki 1 Ch.2 Part 4 of 5",
            partNumber: 4,
            totalParts: 5,
            description: "Money and Shopping",
            isImported: false,
          },
          {
            id: "genki-1-ch2-p5",
            name: "Genki 1 Ch.2 Part 5 of 5",
            partNumber: 5,
            totalParts: 5,
            description: "Locations and Directions",
            isImported: false,
          },
        ],
      },
    ],
  },
  {
    id: "genki-2",
    name: "Genki II: An Integrated Course in Elementary Japanese",
    short_name: "Genki II",
    chapters: [
      {
        id: "genki-2-ch13",
        number: 13,
        title: "Looking for a Part-time Job",
        parts: [
          {
            id: "genki-2-ch13-p1",
            name: "Genki 2 Ch.13 Part 1 of 4",
            partNumber: 1,
            totalParts: 4,
            description: "Jobs and Work",
            isImported: false,
          },
          {
            id: "genki-2-ch13-p2",
            name: "Genki 2 Ch.13 Part 2 of 4",
            partNumber: 2,
            totalParts: 4,
            description: "Skills and Abilities",
            isImported: false,
          },
          {
            id: "genki-2-ch13-p3",
            name: "Genki 2 Ch.13 Part 3 of 4",
            partNumber: 3,
            totalParts: 4,
            description: "Experience and Qualifications",
            isImported: false,
          },
          {
            id: "genki-2-ch13-p4",
            name: "Genki 2 Ch.13 Part 4 of 4",
            partNumber: 4,
            totalParts: 4,
            description: "Interview and Application",
            isImported: false,
          },
        ],
      },
      {
        id: "genki-2-ch14",
        number: 14,
        title: "Looking for an Apartment",
        parts: [
          {
            id: "genki-2-ch14-p1",
            name: "Genki 2 Ch.14 Part 1 of 4",
            partNumber: 1,
            totalParts: 4,
            description: "Housing and Rooms",
            isImported: false,
          },
          {
            id: "genki-2-ch14-p2",
            name: "Genki 2 Ch.14 Part 2 of 4",
            partNumber: 2,
            totalParts: 4,
            description: "Furniture and Appliances",
            isImported: false,
          },
          {
            id: "genki-2-ch14-p3",
            name: "Genki 2 Ch.14 Part 3 of 4",
            partNumber: 3,
            totalParts: 4,
            description: "Moving and Lifestyle",
            isImported: false,
          },
          {
            id: "genki-2-ch14-p4",
            name: "Genki 2 Ch.14 Part 4 of 4",
            partNumber: 4,
            totalParts: 4,
            description: "Rent and Contracts",
            isImported: false,
          },
        ],
      },
    ],
  },
]
