// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

import type {} from '@useautumn/sdk';

declare module '@useautumn/sdk' {
  // Features
  export const built_in_srs: Feature;

  // Plans
  export const pro_plan: Plan;

  // Base types
  export type Feature = import('./autumn.config').Feature;
  export type Plan = import('./autumn.config').Plan;
}
