/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ANILIST_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ANILIST_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAL_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "SECRET_VAL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_PUBLISHABLE_OR_ANON_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}