import type { ConjugatedWord } from "../../../src/features/sentence-practice/core/conjugation/types"

export type SegmentConjugation = {
  pos: ConjugatedWord["pos"]
  form?: ConjugatedWord["form"]
  polarity: ConjugatedWord["polarity"]
  tense: ConjugatedWord["tense"]
}

export type Segment = {
  text: string
  blank?: boolean
  conjugation?: SegmentConjugation
}

export type Answer = {
  segments: Segment[]
  notes?: string
  register?: "polite" | "casual"
}

export type Question = {
  english: string
  hint?: string
  answers: Answer[]
  // preparedAnswerTokens is auto-generated by the seed script, not stored in source
}
