export type Segment = {
  text: string
  blank?: boolean
  conjugation?: {
    pos: string
    form?: string
    polarity: "positive" | "negative"
    tense: "past" | "non-past"
  }
}

export type Answer = {
  segments: Segment[]
  notes?: string
}

export type Question = {
  english: string
  hint?: string
  answers: Answer[]
  // modelAnswerPOS is auto-generated by the seed script, not stored in source
}
