/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/solid-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as LearnIndexImport } from './routes/learn/index'
import { Route as LearnLearnImport } from './routes/learn/_learn'
import { Route as LearnLearnVocabularyImport } from './routes/learn/_learn/vocabulary'

// Create Virtual Routes

const LearnImport = createFileRoute('/learn')()

// Create/Update Routes

const LearnRoute = LearnImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LearnIndexRoute = LearnIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)

const LearnLearnRoute = LearnLearnImport.update({
  id: '/_learn',
  getParentRoute: () => LearnRoute,
} as any)

const LearnLearnVocabularyRoute = LearnLearnVocabularyImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => LearnLearnRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnImport
      parentRoute: typeof rootRoute
    }
    '/learn/_learn': {
      id: '/learn/_learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnLearnImport
      parentRoute: typeof LearnRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexImport
      parentRoute: typeof LearnImport
    }
    '/learn/_learn/vocabulary': {
      id: '/learn/_learn/vocabulary'
      path: '/vocabulary'
      fullPath: '/learn/vocabulary'
      preLoaderRoute: typeof LearnLearnVocabularyImport
      parentRoute: typeof LearnLearnImport
    }
  }
}

// Create and export the route tree

interface LearnLearnRouteChildren {
  LearnLearnVocabularyRoute: typeof LearnLearnVocabularyRoute
}

const LearnLearnRouteChildren: LearnLearnRouteChildren = {
  LearnLearnVocabularyRoute: LearnLearnVocabularyRoute,
}

const LearnLearnRouteWithChildren = LearnLearnRoute._addFileChildren(
  LearnLearnRouteChildren,
)

interface LearnRouteChildren {
  LearnLearnRoute: typeof LearnLearnRouteWithChildren
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnLearnRoute: LearnLearnRouteWithChildren,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnLearnRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/vocabulary': typeof LearnLearnVocabularyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnIndexRoute
  '/learn/vocabulary': typeof LearnLearnVocabularyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn/_learn': typeof LearnLearnRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/_learn/vocabulary': typeof LearnLearnVocabularyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/learn/'
    | '/learn/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/learn' | '/learn/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/learn/_learn'
    | '/learn/'
    | '/learn/_learn/vocabulary'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard",
        "/learn"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/learn": {
      "filePath": "learn",
      "children": [
        "/learn/_learn",
        "/learn/"
      ]
    },
    "/learn/_learn": {
      "filePath": "learn/_learn.tsx",
      "parent": "/learn",
      "children": [
        "/learn/_learn/vocabulary"
      ]
    },
    "/learn/": {
      "filePath": "learn/index.tsx",
      "parent": "/learn"
    },
    "/learn/_learn/vocabulary": {
      "filePath": "learn/_learn/vocabulary.tsx",
      "parent": "/learn/_learn"
    }
  }
}
ROUTE_MANIFEST_END */
