/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LearnImport } from './routes/learn'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as LearnIndexImport } from './routes/learn/index'
import { Route as LearnVocabularyImport } from './routes/learn/vocabulary'
import { Route as LearnLessonsWelcomeOverviewImport } from './routes/learn/_lessons/welcome-overview'

// Create/Update Routes

const LearnRoute = LearnImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LearnIndexRoute = LearnIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)

const LearnVocabularyRoute = LearnVocabularyImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => LearnRoute,
} as any)

const LearnLessonsWelcomeOverviewRoute =
  LearnLessonsWelcomeOverviewImport.update({
    id: '/_lessons/welcome-overview',
    path: '/welcome-overview',
    getParentRoute: () => LearnRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnImport
      parentRoute: typeof rootRoute
    }
    '/learn/vocabulary': {
      id: '/learn/vocabulary'
      path: '/vocabulary'
      fullPath: '/learn/vocabulary'
      preLoaderRoute: typeof LearnVocabularyImport
      parentRoute: typeof LearnImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexImport
      parentRoute: typeof LearnImport
    }
    '/learn/_lessons/welcome-overview': {
      id: '/learn/_lessons/welcome-overview'
      path: '/welcome-overview'
      fullPath: '/learn/welcome-overview'
      preLoaderRoute: typeof LearnLessonsWelcomeOverviewImport
      parentRoute: typeof LearnImport
    }
  }
}

// Create and export the route tree

interface LearnRouteChildren {
  LearnVocabularyRoute: typeof LearnVocabularyRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnLessonsWelcomeOverviewRoute: typeof LearnLessonsWelcomeOverviewRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnVocabularyRoute: LearnVocabularyRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnLessonsWelcomeOverviewRoute: LearnLessonsWelcomeOverviewRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn/vocabulary': typeof LearnVocabularyRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/welcome-overview': typeof LearnLessonsWelcomeOverviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn/vocabulary': typeof LearnVocabularyRoute
  '/learn': typeof LearnIndexRoute
  '/learn/welcome-overview': typeof LearnLessonsWelcomeOverviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn/vocabulary': typeof LearnVocabularyRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/_lessons/welcome-overview': typeof LearnLessonsWelcomeOverviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/learn/vocabulary'
    | '/learn/'
    | '/learn/welcome-overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learn/vocabulary'
    | '/learn'
    | '/learn/welcome-overview'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/learn/vocabulary'
    | '/learn/'
    | '/learn/_lessons/welcome-overview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard",
        "/learn"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/learn": {
      "filePath": "learn.tsx",
      "children": [
        "/learn/vocabulary",
        "/learn/",
        "/learn/_lessons/welcome-overview"
      ]
    },
    "/learn/vocabulary": {
      "filePath": "learn/vocabulary.tsx",
      "parent": "/learn"
    },
    "/learn/": {
      "filePath": "learn/index.tsx",
      "parent": "/learn"
    },
    "/learn/_lessons/welcome-overview": {
      "filePath": "learn/_lessons/welcome-overview.tsx",
      "parent": "/learn"
    }
  }
}
ROUTE_MANIFEST_END */
