/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/solid-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as KanjiTestRouteImport } from './routes/kanji-test'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeReviewRouteImport } from './routes/practice/review'
import { Route as PracticeHiraganaQuizRouteImport } from './routes/practice/hiragana-quiz'
import { Route as PracticeDakutenHandakutenQuizRouteImport } from './routes/practice/dakuten-handakuten-quiz'
import { Route as PracticeContractedSoundsQuizRouteImport } from './routes/practice/contracted-sounds-quiz'
import { Route as PracticeAllHiraganaQuizRouteImport } from './routes/practice/all-hiragana-quiz'
import { Route as PracticePracticeIDRouteImport } from './routes/practice/$practiceID'
import { Route as LessonsWritingSystemsRouteImport } from './routes/lessons/writing-systems'
import { Route as LessonsWelcomeOverviewRouteImport } from './routes/lessons/welcome-overview'
import { Route as LessonsJapanesePronunciationRouteImport } from './routes/lessons/japanese-pronunciation'
import { Route as LessonsHiraganaRouteImport } from './routes/lessons/hiragana'
import { Route as HomeVocabRouteImport } from './routes/_home/vocab'
import { Route as HomeSentencePracticeRouteImport } from './routes/_home/sentence-practice'
import { Route as HomeGrammarNotesRouteImport } from './routes/_home/grammar-notes'
import { Route as HomeDashboardRouteImport } from './routes/_home/dashboard'
import { Route as HomeConjugationRouteImport } from './routes/_home/conjugation'
import { Route as HomeLearnIndexRouteImport } from './routes/_home/learn/index'
import { Route as HomeLearnTextbookIdChapterSlugRouteImport } from './routes/_home/learn/$textbookId.$chapterSlug'
import { ServerRoute as ApiHelloServerRouteImport } from './routes/api/hello'
import { ServerRoute as ApiAuthLogoutServerRouteImport } from './routes/api/auth/logout'
import { ServerRoute as ApiAuthLoginServerRouteImport } from './routes/api/auth/login'

const rootServerRouteImport = createServerRootRoute()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiTestRoute = KanjiTestRouteImport.update({
  id: '/kanji-test',
  path: '/kanji-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeReviewRoute = PracticeReviewRouteImport.update({
  id: '/practice/review',
  path: '/practice/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeHiraganaQuizRoute = PracticeHiraganaQuizRouteImport.update({
  id: '/practice/hiragana-quiz',
  path: '/practice/hiragana-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeDakutenHandakutenQuizRoute =
  PracticeDakutenHandakutenQuizRouteImport.update({
    id: '/practice/dakuten-handakuten-quiz',
    path: '/practice/dakuten-handakuten-quiz',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeContractedSoundsQuizRoute =
  PracticeContractedSoundsQuizRouteImport.update({
    id: '/practice/contracted-sounds-quiz',
    path: '/practice/contracted-sounds-quiz',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeAllHiraganaQuizRoute = PracticeAllHiraganaQuizRouteImport.update({
  id: '/practice/all-hiragana-quiz',
  path: '/practice/all-hiragana-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticePracticeIDRoute = PracticePracticeIDRouteImport.update({
  id: '/practice/$practiceID',
  path: '/practice/$practiceID',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsWritingSystemsRoute = LessonsWritingSystemsRouteImport.update({
  id: '/writing-systems',
  path: '/writing-systems',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsWelcomeOverviewRoute = LessonsWelcomeOverviewRouteImport.update({
  id: '/welcome-overview',
  path: '/welcome-overview',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsJapanesePronunciationRoute =
  LessonsJapanesePronunciationRouteImport.update({
    id: '/japanese-pronunciation',
    path: '/japanese-pronunciation',
    getParentRoute: () => LessonsRoute,
  } as any)
const LessonsHiraganaRoute = LessonsHiraganaRouteImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => LessonsRoute,
} as any)
const HomeVocabRoute = HomeVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => HomeRoute,
} as any)
const HomeSentencePracticeRoute = HomeSentencePracticeRouteImport.update({
  id: '/sentence-practice',
  path: '/sentence-practice',
  getParentRoute: () => HomeRoute,
} as any)
const HomeGrammarNotesRoute = HomeGrammarNotesRouteImport.update({
  id: '/grammar-notes',
  path: '/grammar-notes',
  getParentRoute: () => HomeRoute,
} as any)
const HomeDashboardRoute = HomeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRoute,
} as any)
const HomeConjugationRoute = HomeConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLearnIndexRoute = HomeLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLearnTextbookIdChapterSlugRoute =
  HomeLearnTextbookIdChapterSlugRouteImport.update({
    id: '/learn/$textbookId/$chapterSlug',
    path: '/learn/$textbookId/$chapterSlug',
    getParentRoute: () => HomeRoute,
  } as any)
const ApiHelloServerRoute = ApiHelloServerRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthLogoutServerRoute = ApiAuthLogoutServerRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthLoginServerRoute = ApiAuthLoginServerRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kanji-test': typeof KanjiTestRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/conjugation': typeof HomeConjugationRoute
  '/dashboard': typeof HomeDashboardRoute
  '/grammar-notes': typeof HomeGrammarNotesRoute
  '/sentence-practice': typeof HomeSentencePracticeRoute
  '/vocab': typeof HomeVocabRoute
  '/lessons/hiragana': typeof LessonsHiraganaRoute
  '/lessons/japanese-pronunciation': typeof LessonsJapanesePronunciationRoute
  '/lessons/welcome-overview': typeof LessonsWelcomeOverviewRoute
  '/lessons/writing-systems': typeof LessonsWritingSystemsRoute
  '/practice/$practiceID': typeof PracticePracticeIDRoute
  '/practice/all-hiragana-quiz': typeof PracticeAllHiraganaQuizRoute
  '/practice/contracted-sounds-quiz': typeof PracticeContractedSoundsQuizRoute
  '/practice/dakuten-handakuten-quiz': typeof PracticeDakutenHandakutenQuizRoute
  '/practice/hiragana-quiz': typeof PracticeHiraganaQuizRoute
  '/practice/review': typeof PracticeReviewRoute
  '/learn': typeof HomeLearnIndexRoute
  '/learn/$textbookId/$chapterSlug': typeof HomeLearnTextbookIdChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kanji-test': typeof KanjiTestRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/conjugation': typeof HomeConjugationRoute
  '/dashboard': typeof HomeDashboardRoute
  '/grammar-notes': typeof HomeGrammarNotesRoute
  '/sentence-practice': typeof HomeSentencePracticeRoute
  '/vocab': typeof HomeVocabRoute
  '/lessons/hiragana': typeof LessonsHiraganaRoute
  '/lessons/japanese-pronunciation': typeof LessonsJapanesePronunciationRoute
  '/lessons/welcome-overview': typeof LessonsWelcomeOverviewRoute
  '/lessons/writing-systems': typeof LessonsWritingSystemsRoute
  '/practice/$practiceID': typeof PracticePracticeIDRoute
  '/practice/all-hiragana-quiz': typeof PracticeAllHiraganaQuizRoute
  '/practice/contracted-sounds-quiz': typeof PracticeContractedSoundsQuizRoute
  '/practice/dakuten-handakuten-quiz': typeof PracticeDakutenHandakutenQuizRoute
  '/practice/hiragana-quiz': typeof PracticeHiraganaQuizRoute
  '/practice/review': typeof PracticeReviewRoute
  '/learn': typeof HomeLearnIndexRoute
  '/learn/$textbookId/$chapterSlug': typeof HomeLearnTextbookIdChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteWithChildren
  '/auth': typeof AuthRoute
  '/kanji-test': typeof KanjiTestRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_home/conjugation': typeof HomeConjugationRoute
  '/_home/dashboard': typeof HomeDashboardRoute
  '/_home/grammar-notes': typeof HomeGrammarNotesRoute
  '/_home/sentence-practice': typeof HomeSentencePracticeRoute
  '/_home/vocab': typeof HomeVocabRoute
  '/lessons/hiragana': typeof LessonsHiraganaRoute
  '/lessons/japanese-pronunciation': typeof LessonsJapanesePronunciationRoute
  '/lessons/welcome-overview': typeof LessonsWelcomeOverviewRoute
  '/lessons/writing-systems': typeof LessonsWritingSystemsRoute
  '/practice/$practiceID': typeof PracticePracticeIDRoute
  '/practice/all-hiragana-quiz': typeof PracticeAllHiraganaQuizRoute
  '/practice/contracted-sounds-quiz': typeof PracticeContractedSoundsQuizRoute
  '/practice/dakuten-handakuten-quiz': typeof PracticeDakutenHandakutenQuizRoute
  '/practice/hiragana-quiz': typeof PracticeHiraganaQuizRoute
  '/practice/review': typeof PracticeReviewRoute
  '/_home/learn/': typeof HomeLearnIndexRoute
  '/_home/learn/$textbookId/$chapterSlug': typeof HomeLearnTextbookIdChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kanji-test'
    | '/lessons'
    | '/settings'
    | '/conjugation'
    | '/dashboard'
    | '/grammar-notes'
    | '/sentence-practice'
    | '/vocab'
    | '/lessons/hiragana'
    | '/lessons/japanese-pronunciation'
    | '/lessons/welcome-overview'
    | '/lessons/writing-systems'
    | '/practice/$practiceID'
    | '/practice/all-hiragana-quiz'
    | '/practice/contracted-sounds-quiz'
    | '/practice/dakuten-handakuten-quiz'
    | '/practice/hiragana-quiz'
    | '/practice/review'
    | '/learn'
    | '/learn/$textbookId/$chapterSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kanji-test'
    | '/lessons'
    | '/settings'
    | '/conjugation'
    | '/dashboard'
    | '/grammar-notes'
    | '/sentence-practice'
    | '/vocab'
    | '/lessons/hiragana'
    | '/lessons/japanese-pronunciation'
    | '/lessons/welcome-overview'
    | '/lessons/writing-systems'
    | '/practice/$practiceID'
    | '/practice/all-hiragana-quiz'
    | '/practice/contracted-sounds-quiz'
    | '/practice/dakuten-handakuten-quiz'
    | '/practice/hiragana-quiz'
    | '/practice/review'
    | '/learn'
    | '/learn/$textbookId/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/auth'
    | '/kanji-test'
    | '/lessons'
    | '/settings'
    | '/_home/conjugation'
    | '/_home/dashboard'
    | '/_home/grammar-notes'
    | '/_home/sentence-practice'
    | '/_home/vocab'
    | '/lessons/hiragana'
    | '/lessons/japanese-pronunciation'
    | '/lessons/welcome-overview'
    | '/lessons/writing-systems'
    | '/practice/$practiceID'
    | '/practice/all-hiragana-quiz'
    | '/practice/contracted-sounds-quiz'
    | '/practice/dakuten-handakuten-quiz'
    | '/practice/hiragana-quiz'
    | '/practice/review'
    | '/_home/learn/'
    | '/_home/learn/$textbookId/$chapterSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  AuthRoute: typeof AuthRoute
  KanjiTestRoute: typeof KanjiTestRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  PracticePracticeIDRoute: typeof PracticePracticeIDRoute
  PracticeAllHiraganaQuizRoute: typeof PracticeAllHiraganaQuizRoute
  PracticeContractedSoundsQuizRoute: typeof PracticeContractedSoundsQuizRoute
  PracticeDakutenHandakutenQuizRoute: typeof PracticeDakutenHandakutenQuizRoute
  PracticeHiraganaQuizRoute: typeof PracticeHiraganaQuizRoute
  PracticeReviewRoute: typeof PracticeReviewRoute
}
export interface FileServerRoutesByFullPath {
  '/api/hello': typeof ApiHelloServerRoute
  '/api/auth/login': typeof ApiAuthLoginServerRoute
  '/api/auth/logout': typeof ApiAuthLogoutServerRoute
}
export interface FileServerRoutesByTo {
  '/api/hello': typeof ApiHelloServerRoute
  '/api/auth/login': typeof ApiAuthLoginServerRoute
  '/api/auth/logout': typeof ApiAuthLogoutServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/hello': typeof ApiHelloServerRoute
  '/api/auth/login': typeof ApiAuthLoginServerRoute
  '/api/auth/logout': typeof ApiAuthLogoutServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/hello' | '/api/auth/login' | '/api/auth/logout'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/hello' | '/api/auth/login' | '/api/auth/logout'
  id: '__root__' | '/api/hello' | '/api/auth/login' | '/api/auth/logout'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiHelloServerRoute: typeof ApiHelloServerRoute
  ApiAuthLoginServerRoute: typeof ApiAuthLoginServerRoute
  ApiAuthLogoutServerRoute: typeof ApiAuthLogoutServerRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji-test': {
      id: '/kanji-test'
      path: '/kanji-test'
      fullPath: '/kanji-test'
      preLoaderRoute: typeof KanjiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/review': {
      id: '/practice/review'
      path: '/practice/review'
      fullPath: '/practice/review'
      preLoaderRoute: typeof PracticeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/hiragana-quiz': {
      id: '/practice/hiragana-quiz'
      path: '/practice/hiragana-quiz'
      fullPath: '/practice/hiragana-quiz'
      preLoaderRoute: typeof PracticeHiraganaQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/dakuten-handakuten-quiz': {
      id: '/practice/dakuten-handakuten-quiz'
      path: '/practice/dakuten-handakuten-quiz'
      fullPath: '/practice/dakuten-handakuten-quiz'
      preLoaderRoute: typeof PracticeDakutenHandakutenQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/contracted-sounds-quiz': {
      id: '/practice/contracted-sounds-quiz'
      path: '/practice/contracted-sounds-quiz'
      fullPath: '/practice/contracted-sounds-quiz'
      preLoaderRoute: typeof PracticeContractedSoundsQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/all-hiragana-quiz': {
      id: '/practice/all-hiragana-quiz'
      path: '/practice/all-hiragana-quiz'
      fullPath: '/practice/all-hiragana-quiz'
      preLoaderRoute: typeof PracticeAllHiraganaQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$practiceID': {
      id: '/practice/$practiceID'
      path: '/practice/$practiceID'
      fullPath: '/practice/$practiceID'
      preLoaderRoute: typeof PracticePracticeIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/writing-systems': {
      id: '/lessons/writing-systems'
      path: '/writing-systems'
      fullPath: '/lessons/writing-systems'
      preLoaderRoute: typeof LessonsWritingSystemsRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/welcome-overview': {
      id: '/lessons/welcome-overview'
      path: '/welcome-overview'
      fullPath: '/lessons/welcome-overview'
      preLoaderRoute: typeof LessonsWelcomeOverviewRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/japanese-pronunciation': {
      id: '/lessons/japanese-pronunciation'
      path: '/japanese-pronunciation'
      fullPath: '/lessons/japanese-pronunciation'
      preLoaderRoute: typeof LessonsJapanesePronunciationRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/hiragana': {
      id: '/lessons/hiragana'
      path: '/hiragana'
      fullPath: '/lessons/hiragana'
      preLoaderRoute: typeof LessonsHiraganaRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/_home/vocab': {
      id: '/_home/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof HomeVocabRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/sentence-practice': {
      id: '/_home/sentence-practice'
      path: '/sentence-practice'
      fullPath: '/sentence-practice'
      preLoaderRoute: typeof HomeSentencePracticeRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/grammar-notes': {
      id: '/_home/grammar-notes'
      path: '/grammar-notes'
      fullPath: '/grammar-notes'
      preLoaderRoute: typeof HomeGrammarNotesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/dashboard': {
      id: '/_home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HomeDashboardRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/conjugation': {
      id: '/_home/conjugation'
      path: '/conjugation'
      fullPath: '/conjugation'
      preLoaderRoute: typeof HomeConjugationRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/learn/': {
      id: '/_home/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof HomeLearnIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/learn/$textbookId/$chapterSlug': {
      id: '/_home/learn/$textbookId/$chapterSlug'
      path: '/learn/$textbookId/$chapterSlug'
      fullPath: '/learn/$textbookId/$chapterSlug'
      preLoaderRoute: typeof HomeLearnTextbookIdChapterSlugRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}
declare module '@tanstack/solid-start/server' {
  interface ServerFileRoutesByPath {
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface HomeRouteChildren {
  HomeConjugationRoute: typeof HomeConjugationRoute
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeGrammarNotesRoute: typeof HomeGrammarNotesRoute
  HomeSentencePracticeRoute: typeof HomeSentencePracticeRoute
  HomeVocabRoute: typeof HomeVocabRoute
  HomeLearnIndexRoute: typeof HomeLearnIndexRoute
  HomeLearnTextbookIdChapterSlugRoute: typeof HomeLearnTextbookIdChapterSlugRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeConjugationRoute: HomeConjugationRoute,
  HomeDashboardRoute: HomeDashboardRoute,
  HomeGrammarNotesRoute: HomeGrammarNotesRoute,
  HomeSentencePracticeRoute: HomeSentencePracticeRoute,
  HomeVocabRoute: HomeVocabRoute,
  HomeLearnIndexRoute: HomeLearnIndexRoute,
  HomeLearnTextbookIdChapterSlugRoute: HomeLearnTextbookIdChapterSlugRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface LessonsRouteChildren {
  LessonsHiraganaRoute: typeof LessonsHiraganaRoute
  LessonsJapanesePronunciationRoute: typeof LessonsJapanesePronunciationRoute
  LessonsWelcomeOverviewRoute: typeof LessonsWelcomeOverviewRoute
  LessonsWritingSystemsRoute: typeof LessonsWritingSystemsRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsHiraganaRoute: LessonsHiraganaRoute,
  LessonsJapanesePronunciationRoute: LessonsJapanesePronunciationRoute,
  LessonsWelcomeOverviewRoute: LessonsWelcomeOverviewRoute,
  LessonsWritingSystemsRoute: LessonsWritingSystemsRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  AuthRoute: AuthRoute,
  KanjiTestRoute: KanjiTestRoute,
  LessonsRoute: LessonsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  PracticePracticeIDRoute: PracticePracticeIDRoute,
  PracticeAllHiraganaQuizRoute: PracticeAllHiraganaQuizRoute,
  PracticeContractedSoundsQuizRoute: PracticeContractedSoundsQuizRoute,
  PracticeDakutenHandakutenQuizRoute: PracticeDakutenHandakutenQuizRoute,
  PracticeHiraganaQuizRoute: PracticeHiraganaQuizRoute,
  PracticeReviewRoute: PracticeReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHelloServerRoute: ApiHelloServerRoute,
  ApiAuthLoginServerRoute: ApiAuthLoginServerRoute,
  ApiAuthLogoutServerRoute: ApiAuthLogoutServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
