export const TOOLS = [
  {
    id: "vocab",
    title: "Vocabulary",
    description: "Master words with spaced repetition",
    href: "/vocab",
    icon: "語",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10 hover:bg-orange-500/20",
    borderColor: "hover:border-orange-500/30",
  },
  {
    id: "sentences",
    title: "Sentences",
    description: "Practice grammar patterns",
    href: "/sentence-practice",
    icon: "文",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    borderColor: "hover:border-amber-500/30",
  },
  {
    id: "conjugation",
    title: "Conjugation",
    description: "Drill all verb forms",
    href: "/practice/conjugation",
    icon: "鍛",
    color: "text-teal-400",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "hover:border-teal-500/30",
  },
  {
    id: "kana",
    title: "Kana",
    description: "Learn hiragana & katakana",
    href: "/kana",
    icon: "あ",
    color: "text-sky-400",
    bgColor: "bg-sky-500/10 hover:bg-sky-500/20",
    borderColor: "hover:border-sky-500/30",
  },
  {
    id: "counters",
    title: "Counters",
    description: "Master Japanese counters",
    href: "/counters",
    icon: "計",
    color: "text-green-400",
    bgColor: "bg-green-500/10 hover:bg-green-500/20",
    borderColor: "hover:border-green-500/30",
  },
  {
    id: "cheatsheets",
    title: "Cheatsheets",
    description: "Quick reference guides",
    href: "/cheatsheets",
    icon: "📋",
    color: "text-rose-400",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "hover:border-rose-500/30",
  },
] as const

export type Tool = (typeof TOOLS)[number]
